### ISSUE TITLE
please remove me from deployment approvers

### ISSUE THREAD

**Issue by MicaiahReid** [hirosystems/stacks-devnet-api#109]
Hey fam @hugocaillard @leahjlou @smcclellan 

I think I'm still listed as one of the Environment maintainers or something for this repo - whenever a new image is built and ready to be deployed to dev/stg/prd, I get a notification requesting my approval.

I can't actually give approval to auto-deploy, so I don't think there are any security implications here, but I still figured you don't want me on that list 🙂 

Thanks Hiros!

**Comment by leahjlou** [comment]
Thanks for letting us know, I believe I've removed you (and Ludo) now! Let me know if you see any other pings about this.

**Comment by MicaiahReid** [comment]
Thanks @leahjlou!

And I miss all of you Hiros too, @diwakergupta ❤
