### ISSUE TITLE
Add status or health page

### ISSUE THREAD

**Issue by CharlieC3** [hirosystems/stacks-devnet-api#59]
For checking the availability of the service, it would be helpful to have a status/health page that's pingable and reports the overall health of the app. It could be located at a path like `/status` or `/api/v1/status`, wherever you think is best.
GET requests to the root path (`/`) should automatically redirect to this status page.

**Comment by MicaiahReid** [comment]
@CharlieC3 do you have any thoughts on what kind of health metrics we'd want to support?

**Comment by CharlieC3** [comment]
@MicaiahReid Hmm it doesn't have to have anything fancy in it to start, but it would be very helpful if it printed the release version, similar to the Stacks Blockchain API's [status page](https://api.hiro.so/extended/v1/status).
Another idea is that it could report k8s api connectivity issues after X failures.
